# Generated by Django 5.0.4 on 2024-11-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSalaryPaymentModel',
            new_name='TeacherSalaryModel',
        ),
    ]
